//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ChatProto.proto
namespace chat
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"prototest")]
  public partial class prototest : global::ProtoBuf.IExtensible
  {
    public prototest() {}
    
    private float _m_score;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_score", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float m_score
    {
      get { return _m_score; }
      set { _m_score = value; }
    }
    private double _m_double;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_double", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double m_double
    {
      get { return _m_double; }
      set { _m_double = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Login")]
  public partial class Login : global::ProtoBuf.IExtensible
  {
    public Login() {}
    
    private int _m_nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nUserID
    {
      get { return _m_nUserID; }
      set { _m_nUserID = value; }
    }
    private string _m_strNickName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_strNickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strNickName
    {
      get { return _m_strNickName; }
      set { _m_strNickName = value; }
    }
    private string _m_strKey;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_strKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strKey
    {
      get { return _m_strKey; }
      set { _m_strKey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoom")]
  public partial class CreateRoom : global::ProtoBuf.IExtensible
  {
    public CreateRoom() {}
    
    private int _m_nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nUserID
    {
      get { return _m_nUserID; }
      set { _m_nUserID = value; }
    }
    private string _m_strRoomName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_strRoomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strRoomName
    {
      get { return _m_strRoomName; }
      set { _m_strRoomName = value; }
    }
    private string _m_strKey;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_strKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strKey
    {
      get { return _m_strKey; }
      set { _m_strKey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserChat")]
  public partial class UserChat : global::ProtoBuf.IExtensible
  {
    public UserChat() {}
    
    private int _m_nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nUserID
    {
      get { return _m_nUserID; }
      set { _m_nUserID = value; }
    }
    private string _m_strNickName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"m_strNickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string m_strNickName
    {
      get { return _m_strNickName; }
      set { _m_strNickName = value; }
    }
    private string _m_strMessage;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_strMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strMessage
    {
      get { return _m_strMessage; }
      set { _m_strMessage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignUpResponse")]
  public partial class SignUpResponse : global::ProtoBuf.IExtensible
  {
    public SignUpResponse() {}
    
    private int _errorCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private float _version = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogonReqMessage")]
  public partial class LogonReqMessage : global::ProtoBuf.IExtensible
  {
    public LogonReqMessage() {}
    
    private long _acctID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"acctID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long acctID
    {
      get { return _acctID; }
      set { _acctID = value; }
    }
    private string _passwd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"passwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passwd
    {
      get { return _passwd; }
      set { _passwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfo")]
  public partial class UserInfo : global::ProtoBuf.IExtensible
  {
    public UserInfo() {}
    
    private long _acctID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"acctID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long acctID
    {
      get { return _acctID; }
      set { _acctID = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private chat.UserStatus _status;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public chat.UserStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogonRespMessage")]
  public partial class LogonRespMessage : global::ProtoBuf.IExtensible
  {
    public LogonRespMessage() {}
    
    private bool _logonResult;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"logonResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool logonResult
    {
      get { return _logonResult; }
      set { _logonResult = value; }
    }
    private chat.UserInfo _userInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public chat.UserInfo userInfo
    {
      get { return _userInfo; }
      set { _userInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"UserStatus")]
    public enum UserStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OFFLINE", Value=0)]
      OFFLINE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ONLINE", Value=1)]
      ONLINE = 1
    }
  
}