//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GameProto.txt
namespace Bjoy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MachineLoginRequest")]
  public partial class MachineLoginRequest : global::ProtoBuf.IExtensible
  {
    public MachineLoginRequest() {}
    
    private string _m_strUUID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_strUUID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strUUID
    {
      get { return _m_strUUID; }
      set { _m_strUUID = value; }
    }
    private string _m_strMacIP;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_strMacIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strMacIP
    {
      get { return _m_strMacIP; }
      set { _m_strMacIP = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MachineLoginRepone")]
  public partial class MachineLoginRepone : global::ProtoBuf.IExtensible
  {
    public MachineLoginRepone() {}
    
    private int _m_nMachineID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_nMachineID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nMachineID
    {
      get { return _m_nMachineID; }
      set { _m_nMachineID = value; }
    }
    private int _m_nHostID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_nHostID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nHostID
    {
      get { return _m_nHostID; }
      set { _m_nHostID = value; }
    }
    private int _m_nProxyIp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_nProxyIp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nProxyIp
    {
      get { return _m_nProxyIp; }
      set { _m_nProxyIp = value; }
    }
    private int _m_nProxyPort;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_nProxyPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nProxyPort
    {
      get { return _m_nProxyPort; }
      set { _m_nProxyPort = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MachineHeartbeatRequest")]
  public partial class MachineHeartbeatRequest : global::ProtoBuf.IExtensible
  {
    public MachineHeartbeatRequest() {}
    
    private int _m_nSeq;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_nSeq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nSeq
    {
      get { return _m_nSeq; }
      set { _m_nSeq = value; }
    }
    private int _m_nTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_nTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nTime
    {
      get { return _m_nTime; }
      set { _m_nTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MachineHeartbeatRespone")]
  public partial class MachineHeartbeatRespone : global::ProtoBuf.IExtensible
  {
    public MachineHeartbeatRespone() {}
    
    private int _m_nSeq;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_nSeq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nSeq
    {
      get { return _m_nSeq; }
      set { _m_nSeq = value; }
    }
    private int _m_nTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_nTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nTime
    {
      get { return _m_nTime; }
      set { _m_nTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserData")]
  public partial class UserData : global::ProtoBuf.IExtensible
  {
    public UserData() {}
    
    private int _m_nUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_nUserID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nUserID
    {
      get { return _m_nUserID; }
      set { _m_nUserID = value; }
    }
    private int _m_nUserCoins;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_nUserCoins", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nUserCoins
    {
      get { return _m_nUserCoins; }
      set { _m_nUserCoins = value; }
    }
    private int _m_nUserIntegrals;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_nUserIntegrals", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nUserIntegrals
    {
      get { return _m_nUserIntegrals; }
      set { _m_nUserIntegrals = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XunLongData")]
  public partial class XunLongData : global::ProtoBuf.IExtensible
  {
    public XunLongData() {}
    
    private int _m_nLevel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_nLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nLevel
    {
      get { return _m_nLevel; }
      set { _m_nLevel = value; }
    }
    private int _m_nExp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_nExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nExp
    {
      get { return _m_nExp; }
      set { _m_nExp = value; }
    }
    private int _m_nNuJian;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_nNuJian", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nNuJian
    {
      get { return _m_nNuJian; }
      set { _m_nNuJian = value; }
    }
    private int _m_nNu;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_nNu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nNu
    {
      get { return _m_nNu; }
      set { _m_nNu = value; }
    }
    private int _m_nLinPian = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"m_nLinPian", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int m_nLinPian
    {
      get { return _m_nLinPian; }
      set { _m_nLinPian = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequest")]
  public partial class LoginRequest : global::ProtoBuf.IExtensible
  {
    public LoginRequest() {}
    
    private int _m_nMachineID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_nMachineID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nMachineID
    {
      get { return _m_nMachineID; }
      set { _m_nMachineID = value; }
    }
    private int _m_nHostID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_nHostID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nHostID
    {
      get { return _m_nHostID; }
      set { _m_nHostID = value; }
    }
    private string _m_strUUID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_strUUID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strUUID
    {
      get { return _m_strUUID; }
      set { _m_strUUID = value; }
    }
    private int _m_nGameType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_nGameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nGameType
    {
      get { return _m_nGameType; }
      set { _m_nGameType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRespone")]
  public partial class LoginRespone : global::ProtoBuf.IExtensible
  {
    public LoginRespone() {}
    
    private string _m_strKey;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_strKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strKey
    {
      get { return _m_strKey; }
      set { _m_strKey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SyncDataRequest")]
  public partial class SyncDataRequest : global::ProtoBuf.IExtensible
  {
    public SyncDataRequest() {}
    
    private string _m_strUserCardID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_strUserCardID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strUserCardID
    {
      get { return _m_strUserCardID; }
      set { _m_strUserCardID = value; }
    }
    private int _m_nGameType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_nGameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nGameType
    {
      get { return _m_nGameType; }
      set { _m_nGameType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SyncDataRespone")]
  public partial class SyncDataRespone : global::ProtoBuf.IExtensible
  {
    public SyncDataRespone() {}
    
    private Bjoy.UserData _m_mUserData;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_mUserData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Bjoy.UserData m_mUserData
    {
      get { return _m_mUserData; }
      set { _m_mUserData = value; }
    }
    private Bjoy.XunLongData _m_mXunLongData;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_mXunLongData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Bjoy.XunLongData m_mXunLongData
    {
      get { return _m_mXunLongData; }
      set { _m_mXunLongData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateUserDataRequest")]
  public partial class UpdateUserDataRequest : global::ProtoBuf.IExtensible
  {
    public UpdateUserDataRequest() {}
    
    private readonly global::System.Collections.Generic.List<Bjoy.UpdateUserDataRequest.GameData> _m_mGameDatas = new global::System.Collections.Generic.List<Bjoy.UpdateUserDataRequest.GameData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"m_mGameDatas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bjoy.UpdateUserDataRequest.GameData> m_mGameDatas
    {
      get { return _m_mGameDatas; }
    }
  
    private int _m_nTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_nTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nTime
    {
      get { return _m_nTime; }
      set { _m_nTime = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameData")]
  public partial class GameData : global::ProtoBuf.IExtensible
  {
    public GameData() {}
    
    private string _m_strCardId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_strCardId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strCardId
    {
      get { return _m_strCardId; }
      set { _m_strCardId = value; }
    }
    private int _m_nIntegrals;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_nIntegrals", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nIntegrals
    {
      get { return _m_nIntegrals; }
      set { _m_nIntegrals = value; }
    }
    private int _m_nExp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_nExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nExp
    {
      get { return _m_nExp; }
      set { _m_nExp = value; }
    }
    private int _m_nNuJian;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"m_nNuJian", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nNuJian
    {
      get { return _m_nNuJian; }
      set { _m_nNuJian = value; }
    }
    private int _m_nLinPian = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"m_nLinPian", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int m_nLinPian
    {
      get { return _m_nLinPian; }
      set { _m_nLinPian = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateUserDataRespone")]
  public partial class UpdateUserDataRespone : global::ProtoBuf.IExtensible
  {
    public UpdateUserDataRespone() {}
    
    private readonly global::System.Collections.Generic.List<Bjoy.UpdateUserDataRespone.UpdateRet> _m_mUpdataRet = new global::System.Collections.Generic.List<Bjoy.UpdateUserDataRespone.UpdateRet>();
    [global::ProtoBuf.ProtoMember(1, Name=@"m_mUpdataRet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Bjoy.UpdateUserDataRespone.UpdateRet> m_mUpdataRet
    {
      get { return _m_mUpdataRet; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateRet")]
  public partial class UpdateRet : global::ProtoBuf.IExtensible
  {
    public UpdateRet() {}
    
    private string _m_strCardID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_strCardID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strCardID
    {
      get { return _m_strCardID; }
      set { _m_strCardID = value; }
    }
    private int _status;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserBuyNuJianRequest")]
  public partial class UserBuyNuJianRequest : global::ProtoBuf.IExtensible
  {
    public UserBuyNuJianRequest() {}
    
    private string _m_strCardID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_strCardID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strCardID
    {
      get { return _m_strCardID; }
      set { _m_strCardID = value; }
    }
    private int _m_nGameType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_nGameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nGameType
    {
      get { return _m_nGameType; }
      set { _m_nGameType = value; }
    }
    private int _m_nTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_nTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nTime
    {
      get { return _m_nTime; }
      set { _m_nTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserBuyNuJianRespone")]
  public partial class UserBuyNuJianRespone : global::ProtoBuf.IExtensible
  {
    public UserBuyNuJianRespone() {}
    
    private string _m_strCardID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"m_strCardID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string m_strCardID
    {
      get { return _m_strCardID; }
      set { _m_strCardID = value; }
    }
    private int _m_nCoins;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"m_nCoins", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nCoins
    {
      get { return _m_nCoins; }
      set { _m_nCoins = value; }
    }
    private int _m_nNuJianShuLiang;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"m_nNuJianShuLiang", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int m_nNuJianShuLiang
    {
      get { return _m_nNuJianShuLiang; }
      set { _m_nNuJianShuLiang = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}